//
// Created by abeeston on 3/28/20.
//

#ifndef COMPILERS_TYPEINDICATOR_H
#define COMPILERS_TYPEINDICATOR_H

enum TypeIndicator {INTEGER, CHAR, STRING, BOOLEAN, ALIAS};
enum LValueType {PRIMITIVE_TYPE, ALIAS_TYPE, ARRAY_TYPE, RECORD_TYPE};

#endif //COMPILERS_TYPEINDICATOR_H
