//
// Created by abeeston on 3/28/20.
//

#ifndef COMPILERS_TYPEINDICATOR_H
#define COMPILERS_TYPEINDICATOR_H

enum PrimitiveType {INTEGER, CHAR, STRING, BOOLEAN, NOT_PRIMITIVE};
enum TypeStyle {SIMPLE, ARRAY, RECORD};
enum EntryStyle {CONSTANT, VARIABLE};
enum PassBy {VALUE, REFERENCE};

#endif //COMPILERS_TYPEINDICATOR_H
